language: php
php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

env:
  global:
  - CORE_BRANCH=stable8.1
  matrix:
  - DB=sqlite

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh contacts $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable contacts

script:
  - cd apps/contacts
  - find . -name \*.php -not -path './l10n/*' -exec php -l "{}" \;
  - phpunit --configuration tests/phpunit.xml --testsuite unit-tests --coverage-clover clover.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

matrix:
  include:
  - php: 5.4
    env: DB=mysql
#  - php: 5.4
#    env: DB=pgsql

  allow_failures:
  - php: hhvm
  fast_finish: true
